name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker  build . -f Dockerfile-py-conda-jupyter -t tzoght/py-conda-jupyter:$(date +%s)
